# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20170306_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 3, 7, 16, 56, 56, 482819, tzinfo=utc)),
        ),
    ]
