# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 17:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20170307_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_images/')),
                ('time', models.DateField(default=datetime.datetime(2017, 3, 7, 17, 32, 22, 823093, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 3, 7, 17, 32, 22, 822593, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='image',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
