# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20170316_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
