# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20170307_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 7, 17, 48, 29, 333410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 3, 7, 17, 48, 29, 333910, tzinfo=utc)),
        ),
    ]
