# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20170318_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='foursquare_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
