# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20170322_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='lng',
            field=models.IntegerField(),
        ),
    ]
