# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20170406_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
    ]
