# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20170408_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='../static/img/profile.jpg', height_field='image_height', upload_to='profile_pictures/', width_field='image_width'),
        ),
    ]
